export const ACTION_TYPES = {
  INCREASE_COUNTER_A: "INCREASE_COUNTER_A",
  INCREASE_COUNTER_B: "INCREASE_COUNTER_B",
  NUMBER_CLICK: "NUMBER_CLICK",
  SWAP_ADDRESS: "SWAP_ADDRESS",
  CHANGE_ACADEMY_NAME: "CHANGE_ACADEMY_NAME",
  USER_FETCH_SUCCEEDED: "USER_FETCH_SUCCEEDED",
  USER_FETCH_FAILED: "USER_FETCH_FAILED",
  USER_FETCH_REQUEST: "USER_FETCH_REQUEST",
}